In [12]:
#Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
#Load Dataset
iris=pd.read_csv('./drugdataset.csv')
iris.head()

Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    1   2            1   25.355  drugY
1   47    0   1            1   13.093  drugC
2   47    0   1            1   10.114  drugC
3   28    1   0            1    7.798  drugX
4   61    1   1            1   18.043  drugY

In [14]:
#Create x and y variables
x=iris.drop('Drug', axis=1).to_numpy()
y=iris['Drug'].to_numpy()

#Create Training and Test Datasets
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x, y, stratify=y,test_size=0.2,random_state=100)

#Scale the Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.transform(x_test)

In [11]:
#Script for SVM and NB
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix  

for name,method in [('SVM', SVC(kernel='linear',random_state=100)),
                    ('Naive Bayes',GaussianNB())]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['drugY', 'drugC', 'drugX', 'drugA', 'drugB']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names))          


Estimator: SVM
[[ 5  0  0  0  0]
 [ 0  2  0  0  1]
 [ 0  0  3  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  1 17]]
              precision    recall  f1-score   support

       drugY       1.00      1.00      1.00         5
       drugC       1.00      0.67      0.80         3
       drugX       1.00      1.00      1.00         3
       drugA       0.92      1.00      0.96        11
       drugB       0.94      0.94      0.94        18

    accuracy                           0.95        40
   macro avg       0.97      0.92      0.94        40
weighted avg       0.95      0.95      0.95        40


Estimator: Naive Bayes
[[ 5  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 10  1]
 [ 1  1  3  1 12]]
              precision    recall  f1-score   support

       drugY       0.83      1.00      0.91         5
       drugC       0.75      1.00      0.86         3
       drugX       0.50      1.00      0.67         3
       drugA       0.91      0.91      0.91        11
       drugB      